export const cards = [
    { id: 1, name: 'product-1', src: '/src/assets/images/product-1.jpg'},
    { id: 2, name: 'product-1', src: '/src/assets/images/product-1.jpg'},
    { id: 3, name: 'product-2', src: '/src/assets/images/product-2.jpg'},
    { id: 4, name: 'product-2', src: '/src/assets/images/product-2.jpg'},
    { id: 5, name: 'product-3', src: '/src/assets/images/product-3.jpg'},
    { id: 6, name: 'product-3', src: '/src/assets/images/product-3.jpg'},
    { id: 7, name: 'product-4', src: '/src/assets/images/product-4.jpg'},
    { id: 8, name: 'product-4', src: '/src/assets/images/product-4.jpg'},
    { id: 9, name: 'product-5', src: '/src/assets/images/product-5.jpg'},
    { id: 10, name: 'product-5', src: '/src/assets/images/product-5.jpg'},
    { id: 11, name: 'product-6', src: '/src/assets/images/product-6.jpg'},
    { id: 12, name: 'product-6', src: '/src/assets/images/product-6.jpg'},
    { id: 13, name: 'product-7', src: '/src/assets/images/product-7.jpg'},
    { id: 14, name: 'product-7', src: '/src/assets/images/product-7.jpg'},
    { id: 15, name: 'product-8', src: '/src/assets/images/product-8.jpg'},
    { id: 16, name: 'product-8', src: '/src/assets/images/product-8.jpg'},
]